config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    resources :pictures
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user

  mount_uploader :image, ImageUploader

  validates :title, :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pictures

  validates :encrypted_password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  if Rails.env.production?
    http_basic_authenticate_with name: Rails.application.credentials[:username_key],
                                 password: Rails.application.credentials[:password_key]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pictures_controller.rb
# frozen_string_literal: true

class PicturesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_ownership

  def index
    @pictures = current_user.pictures
  end

  def new
    @picture = Picture.new(user_id: current_user.id)
  end

  def create
    picture = Picture.new(picture_params)
    if picture.save
      flash[:notice] = 'Picture successfully created'
      redirect_to user_pictures_path(current_user)
    else
      @picture = picture
      render :new
    end
  end

  private

  def ensure_ownership
    redirect_to root_path unless authorized_user?
  end

  def authorized_user?
    current_user && current_user.id == params[:user_id].to_i
  end

  def picture_params
    params.require(:picture).permit(
      :title, :user_id, :image
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def top_menu_link(path, options = {})
    icon_name = options[:icon]
    link_name = options[:name].capitalize
    method = options[:method] || :get
    link_to path, method: method do
      content_tag :span, fa_icon(icon_name, text: link_name)
    end
  end
end

app/views/home/index.html.haml
.text-center
  %h1 Dev App
  .row
    %p Simple Rails application
    %p Devise / Bootstrap / Carrierwave / AWS S3 / RSpec

  - if user_signed_in?
    .row
      %b="Welcome #{current_user.email}!"

app/views/layouts/application.html.haml
%html
  %head
    %title Dev App
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    "application", :media => "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"
%body
  .container
    .content
      = render :partial => "/shared/header"
      = yield

app/views/pictures/_form.html.haml
.form-group.row
  = f.label :title, class: 'col-md-2 control-label'
  .col-md-5
    = f.text_field :title, class: 'form-control'
.form-group.row
  = f.label :image, class: 'col-md-2 control-label'
  .col-md-5
    = f.file_field :image, class: 'form-control'

= hidden_field_tag "picture[user_id]", current_user.id

app/views/pictures/index.html.haml
%h1 Gallery of user pictures

.row
  .new-pictures{ class: "col-lg-12 col-md-12 col-sm-12 col-xs-12" }
    %p= 'No pictures yet' if @pictures.blank?
    %p= link_to('add new picture', new_user_picture_path(current_user))

.row
  - @pictures.each do |picture|
    .user-picture{ class: "col-lg-2 col-md-3 col-sm-4 col-xs-6" }
      %b= picture.title.presence || 'no title'
      %p= image_tag(picture.image.url(:thumb), class: 'rounded')
      %p= picture.created_at.strftime('on %d/%m/%Y')

app/views/pictures/new.html.haml
= form_for @picture, url: user_pictures_path(current_user) do |f|
  %fieldset
    %legend Edit 
    = render partial: 'form', locals: {f: f}

    .form-group.row
      .col-md-offset-2
        .col-md-5
          = f.submit "Save", class: "btn btn-primary"
          = link_to "Cancel", user_pictures_path(current_user), class: "btn btn-link"
    - if f.object.errors.any?
      = render partial: 'shared/errors', locals: {f: f}

app/views/shared/_errors.html.haml
- f.object.errors.full_messages.each do |error|
  .form-group.row.error
    .col-md-offset-2
      .col-md-5
        = error

app/views/shared/_header.html.haml
#menu

%ul.nav.nav-tabs
  %li
    = top_menu_link(root_path, { name: 'home', icon: 'home' })
  - if user_signed_in?
    %li
      = top_menu_link(user_pictures_path(current_user), { name: 'gallery', icon: 'image' })
    %li
      = top_menu_link(destroy_user_session_path, { name: 'logout', icon: 'sign-out-alt', method: :delete })
  - else
    %li
      = top_menu_link(new_user_session_path, { name: 'login', icon: 'sign-in-alt' })

#flash_messages
  %p.notice= notice if flash[:notice].present?
  %p.alert= alert if flash[:alert].present?